# Generated by Django 3.0.7 on 2021-11-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university_connect", "0003_auto_20211124_1249"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("exam_marks", models.FloatField(default=0)),
                ("assignment_marks", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university_connect.Student",
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university_connect.Subject",
                    ),
                ),
            ],
        ),
    ]
