# Generated by Django 3.0.7 on 2021-11-25 17:50

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("university_connect", "0004_studentresult"),
    ]

    operations = [
        migrations.RemoveField(model_name="leavereport", name="dates",),
        migrations.AddField(
            model_name="leavereport",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2021, 11, 26, 17, 50, 45, 758697, tzinfo=utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leavereport",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2021, 11, 25, 17, 50, 55, 736848, tzinfo=utc
                )
            ),
            preserve_default=False,
        ),
    ]
