# Generated by Django 3.0.7 on 2021-11-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university_connect", "0006_auto_20211126_2045"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="read_status",
            field=models.BooleanField(default=False),
        ),
    ]
